#cloud-config-mkdocs-system

groups:
  - ubuntu: [root,sys]
  - dpro42-group

users:
  - default
  - name: spiderman
    gecos: Peter Parker
    shell: /bin/bash
    primary_group: dpro42-group
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9Hq2se/haHEw95rMWnsx9VXlROHBhLG2P2Av31GrdEJse6Fv27SabRntsOii6Kes+YUkHA3PFV0ZxpcLybJYSGqXEoYuO6DTagWO5N6o4nBPGdF8Z8K0pbHV1KV+ywWEKZH1wbPmaUkg76tPvw1K6cBcRaN2lFl7UNUUBJnzCV07r7i4s4P4076/TFJuZVC/z0PWZIPEx2DlcRMLqSV6DjSuQAjkN7Tn3H/KpWaiRVwhMfPIJBJa78TC+KYnFkv7nuPt152pSw5q81rhkJzP1urd9QPg0Hao6vrKRYQew2RnB2U7vxVYhRufC4dMXmS8TF/OeYeHdurgcUPgY7YN7i1CQeqgSB3bLekAClvx+sWuf38j+A3hP1eLFCcQMQLyIv+MZCwgSM1QGJmS0PZvEoEVq4hJQmzYgngknkqf/+xh8noAdwVun7dttgZqZsD4ri5BuVTpMqL61KcdnLqxmcUAfkl+L+9m9KO183h64L/JTuPtCT0F1qma9N44OrMKG6dXke1T03dj5JP0hsjOFolFVf+DJSc5zGQAe42fs7IfxUfRVmy6Bv2qhU/crTxE32ynGYaFDy86aIgz46mpABz24R2SNAsbCQeUdMSUVOnc4bQl+H8coOnC0bravzr+9HrBx2p7KIK16z6hMo+ODnoYCG5VzY7GYeLZutAjJ1Q== vboxuser@debian

runcmd:
  - touch /home/spiderman/hello.txt
  - echo "Hello! and welcome to this server! Destroy me when you are done!" >> /home/spiderman/hello.txt
  - sudo apt-get update
  - sudo apt install apache2 -q -y
  - sudo apt install python3-pip -y
  - sudo pip install mkdocs
  - sudo mkdir /home/spiderman/mkdocs
  - cd /home/spiderman/mkdocs
  - sudo mkdocs new mkdocs-project
  - cd mkdocs-project
  - sudo mkdocs build
  - sudo rm /var/www/html/index.html
  - sudo cp -R site/* /var/www/html
  - sudo systemctl restart apache2
  